version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm install
            npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Build Backend
          command: |
            # Mã xây dựng/compile backend

workflows:
  version: 2
  build:
    jobs:
      - build-frontend
      - build-backend
