version: 2.1

jobs:
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Scan Frontend
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  scan-backend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Scan Backend
          command: |
            # Mã kiểm tra lỗ hổng bảo mật phần backend
            npm install
            npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  build-frontend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm install
            npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Build Backend
          command: |
            # Mã xây dựng phần backend

workflows:
  version: 2
  build:
    jobs:
      - scan-frontend
      - scan-backend:
          requires:
            - scan-frontend
      - build-frontend:
          requires:
            - scan-backend
      - build-backend:
          requires:
            - scan-backend
