version: 2.1

executors:
  default-executor:
    docker:
      - image: amazon/aws-cli

commands:
  destroy-environment:
    steps:
      - run:
          name: Destroy Environment
          command: |
            # Destroy Environment
            aws your-destroy-command

workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build
      - destroy:
          requires:
            - build

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      # deploy

  destroy:
    executor: default-executor
    steps:
      - checkout
      - destroy-environment:
          background: false
